/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SalvosRouteImport } from './routes/salvos'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AnimesAnimeIdRouteImport } from './routes/animes.$animeId'
import { Route as AnimesAnimeIdEpisodeNumberRouteImport } from './routes/animes.$animeId.$episodeNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SalvosRoute = SalvosRouteImport.update({
  id: '/salvos',
  path: '/salvos',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimesAnimeIdRoute = AnimesAnimeIdRouteImport.update({
  id: '/animes/$animeId',
  path: '/animes/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimesAnimeIdEpisodeNumberRoute =
  AnimesAnimeIdEpisodeNumberRouteImport.update({
    id: '/$episodeNumber',
    path: '/$episodeNumber',
    getParentRoute: () => AnimesAnimeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/salvos': typeof SalvosRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/animes/$animeId': typeof AnimesAnimeIdRouteWithChildren
  '/animes/$animeId/$episodeNumber': typeof AnimesAnimeIdEpisodeNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/salvos': typeof SalvosRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/animes/$animeId': typeof AnimesAnimeIdRouteWithChildren
  '/animes/$animeId/$episodeNumber': typeof AnimesAnimeIdEpisodeNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/salvos': typeof SalvosRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/animes/$animeId': typeof AnimesAnimeIdRouteWithChildren
  '/animes/$animeId/$episodeNumber': typeof AnimesAnimeIdEpisodeNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/login'
    | '/register'
    | '/salvos'
    | '/search'
    | '/settings'
    | '/animes/$animeId'
    | '/animes/$animeId/$episodeNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/login'
    | '/register'
    | '/salvos'
    | '/search'
    | '/settings'
    | '/animes/$animeId'
    | '/animes/$animeId/$episodeNumber'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/login'
    | '/register'
    | '/salvos'
    | '/search'
    | '/settings'
    | '/animes/$animeId'
    | '/animes/$animeId/$episodeNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SalvosRoute: typeof SalvosRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AnimesAnimeIdRoute: typeof AnimesAnimeIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salvos': {
      id: '/salvos'
      path: '/salvos'
      fullPath: '/salvos'
      preLoaderRoute: typeof SalvosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animes/$animeId': {
      id: '/animes/$animeId'
      path: '/animes/$animeId'
      fullPath: '/animes/$animeId'
      preLoaderRoute: typeof AnimesAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animes/$animeId/$episodeNumber': {
      id: '/animes/$animeId/$episodeNumber'
      path: '/$episodeNumber'
      fullPath: '/animes/$animeId/$episodeNumber'
      preLoaderRoute: typeof AnimesAnimeIdEpisodeNumberRouteImport
      parentRoute: typeof AnimesAnimeIdRoute
    }
  }
}

interface AnimesAnimeIdRouteChildren {
  AnimesAnimeIdEpisodeNumberRoute: typeof AnimesAnimeIdEpisodeNumberRoute
}

const AnimesAnimeIdRouteChildren: AnimesAnimeIdRouteChildren = {
  AnimesAnimeIdEpisodeNumberRoute: AnimesAnimeIdEpisodeNumberRoute,
}

const AnimesAnimeIdRouteWithChildren = AnimesAnimeIdRoute._addFileChildren(
  AnimesAnimeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SalvosRoute: SalvosRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AnimesAnimeIdRoute: AnimesAnimeIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
